version: '3.7'

services:
  backend:
    build: .
    image: mkznts/classbox-backend:latest
    container_name: "classbox-backend"
    restart: always
    networks:
      - web
      - default
    ports:
      - "8080:8080"
    expose:
      - "8080"
    env_file:
      - secrets.env
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_NAME: postgres
    depends_on:
      - db

  db:
    image: postgres:11.5-alpine
    container_name: "classbox-db"
    env_file:
      - secrets.env
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - classbox-db:/var/lib/postgresql/data
    networks:
      - default

networks:
  web:
    external: true

volumes:
  classbox-db:
    external: true
