version: '3.7'

services:
  api:
    build: .
    image: classbox-api:latest
    container_name: "classbox-api"
    restart: always
    networks:
      - web
      - default
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      DB_HOST: db
      DB_USER: postgres
    depends_on:
      - db

  db:
    image: mkznts/base-postgres:0.1
    container_name: "classbox-db"
    ports:
      - "5432:5432"
    volumes:
      - classbox-db:/var/lib/postgresql/data
      - ./sql:/sql
    environment:
      PGUSER: postgres  # override default user for `psql`
    networks:
      - default

networks:
  web:
    external: true

volumes:
  classbox-db:
    external: true
