version: '3.7'

services:
  api:
    build:
      context: .
      target: base
    image: classbox-base:latest
    container_name: "classbox-api"
    restart: unless-stopped
    networks:
      - web
      - default
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - ADDR=0.0.0.0:8080
      - ENV_TYPE
      - DB_HOST
      - DB_USER
      - GITHUB_OAUTH_CLIENT_ID
      - GITHUB_OAUTH_CLIENT_SECRET
      - GITHUB_APP_ID
      - GITHUB_APP_CLIENT_ID
      - GITHUB_APP_CLIENT_SECRET
      - GITHUB_APP_NAME
      - GITHUB_APP_HOOK_SECRET
      - GITHUB_APP_PRIVATE_KEY
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET
      - WEB_URL
      - JWT_PUBLIC_KEY
      - SENTRY_DSN
      - DEADLINE
    depends_on:
      - db
    command: ["/srv/app", "api"]

  web:
    build:
      context: .
      target: base
    image: classbox-base:latest
    container_name: "classbox-web"
    restart: unless-stopped
    networks:
      - web
      - default
    ports:
      - "8082:8082"
    expose:
      - "8082"
    environment:
      - ADDR=0.0.0.0:8082
      - API_URL=http://api:8080
      - ENV_TYPE
      - DOCS_URL
      - WEB_URL
      - SENTRY_DSN
    depends_on:
      - api
    command: ["/srv/app", "web"]

  tunnel:
    image: mkznts/tunnel:0.1
    container_name: "classbox-tunnel"
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - TUNNEL_URL
      - TUNNEL_TARGET=http://api:8080/tasks/enqueue

  runner:
    build:
      context: .
      target: runner
    image: classbox-runner:latest
    container_name: "classbox-runner"
    restart: unless-stopped
    networks:
      - default
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/srv/data
      - API_URL=http://api:8080
      - ENV_TYPE
      - JWT_PRIVATE_KEY
      - DOCS_URL
      - WEB_URL
      - SENTRY_DSN
      - DOCKER_PULL
      - DOCKER_BUILDER_IMAGE
      - DOCKER_RUNNER_IMAGE
      - DOCKER_LOGIN
      - DOCKER_REPO_USERNAME
      - DOCKER_REPO_PASSWORD
      - DOCKER_REPO_HOST
    depends_on:
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - classbox-data:/srv/data
    command: ["/srv/app", "runner"]

  db:
    image: mkznts/base-postgres:0.3
    container_name: "classbox-db"
    volumes:
      - classbox-db:/var/lib/postgresql/data
      - ./sql:/sql
    environment:
      - PGUSER=${DB_USER}  # override default user for promptless `psql`
    networks:
      - default

  docs:
    image: nginx:1.17.8
    container_name: "classbox-docs"
    volumes:
      - classbox-docs:/usr/share/nginx/html
    ports:
      - "8081:80"
    expose:
      - "8081"
    networks:
      - web

networks:
  web:
    external: true

volumes:
  classbox-db:
    external: true
  classbox-docs:
    external: true
  classbox-data:
    external: true
