version: '3.7'

services:
  api:
    build: .
    image: classbox:latest
    container_name: "classbox-api"
    restart: always
    networks:
      - web
      - default
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - ADDR=0.0.0.0:8080
      - DB_HOST
      - DB_USER
      - GITHUB_OAUTH_CLIENT_ID
      - GITHUB_OAUTH_CLIENT_SECRET
      - GITHUB_APP_ID
      - GITHUB_APP_PRIVATE_KEY
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET
    depends_on:
      - db

  db:
    image: mkznts/base-postgres:0.1
    container_name: "classbox-db"
    ports:
      - "5432:5432"
    volumes:
      - classbox-db:/var/lib/postgresql/data
      - ./sql:/sql
    environment:
      - PGUSER=${DB_USER}  # override default user for promptless `psql`
    networks:
      - default

networks:
  web:
    external: true

volumes:
  classbox-db:
    external: true
