name: Build classbox images
on:
  push:
    branches:
      - master
      - test
    paths:
      - '**'
      - '!*.md'
      - '!sql/*'
    tags:
      - v*
env:
  build_tag: docker.pkg.github.com/mkuznets/classbox/classbox-build
  base_tag: docker.pkg.github.com/mkuznets/classbox/classbox-base
  runner_tag: docker.pkg.github.com/mkuznets/classbox/classbox-runner
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

      - name: Extract branch name
        id: branch
        shell: bash
        run: echo "##[set-output name=name;]$(echo ${GITHUB_REF##*/})"

      - name: checkout
        uses: actions/checkout@v2

      - id: build
        name: docker build
        run: |
          cd $GITHUB_WORKSPACE
          TAG=${GITHUB_REF##*/}

          docker login -u mkuznets -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com

          docker pull ${{ env.build_tag }}:latest || true
          docker pull ${{ env.runner_tag }}:latest || true
          docker pull ${{ env.base_tag }}:latest || true

          docker build . -t ${{ env.build_tag }}:latest --target build --cache-from ${{ env.build_tag }}:latest
          docker build . -t ${{ env.base_tag }}:$TAG --target base --cache-from ${{ env.build_tag }}:latest --cache-from ${{ env.base_tag }}:latest
          docker build . -t ${{ env.runner_tag }}:$TAG --target runner --cache-from ${{ env.build_tag }}:latest --cache-from ${{ env.base_tag }}:$TAG --cache-from ${{ env.runner_tag }}:latest

          docker tag ${{ env.base_tag }}:$TAG ${{ env.base_tag }}:latest
          docker tag ${{ env.runner_tag }}:$TAG ${{ env.runner_tag }}:latest

      - name: docker push
        run: |
          TAG=${GITHUB_REF##*/}

          docker push ${{ env.base_tag }}:$TAG
          docker push ${{ env.base_tag }}:latest
          docker push ${{ env.runner_tag }}:$TAG
          docker push ${{ env.runner_tag }}:latest
          docker push ${{ env.build_tag }}:latest
