name: Build classbox images
on:
  push:
    branches:
      - master
      - test
    paths:
      - '**'
      - '!*.md'
      - '!sql/*'
  create:
env:
  base_tag: docker.pkg.github.com/mkuznets/classbox/classbox-base
  runner_tag: docker.pkg.github.com/mkuznets/classbox/classbox-runner
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

      - name: Extract branch name
        id: branch
        shell: bash
        run: echo "##[set-output name=name;]$(echo ${GITHUB_REF##*/})"

      - name: checkout
        uses: actions/checkout@v2

      - id: build
        name: docker build
        run: |
          cd $GITHUB_WORKSPACE
          docker login -u mkuznets -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com

          docker pull ${{ env.base_tag }}:latest || true
          docker build . -f Dockerfile -t ${{ env.base_tag }}:${{ steps.branch.outputs.name }} --cache-from ${{ env.base_tag }}:latest --target base
          docker tag ${{ env.base_tag }}:${{ steps.branch.outputs.name }} ${{ env.base_tag }}:latest

          docker build . -f Dockerfile -t ${{ env.runner_tag }}:${{ steps.branch.outputs.name }} --cache-from ${{ env.base_tag }}:${{ steps.branch.outputs.name }} --target runner
          docker tag ${{ env.runner_tag }}:${{ steps.branch.outputs.name }} ${{ env.runner_tag }}:latest

      - name: docker push
        run: |
          docker push ${{ env.base_tag }}:${{ steps.branch.outputs.name }}
          docker push ${{ env.base_tag }}:latest

          docker push ${{ env.runner_tag }}:${{ steps.branch.outputs.name }}
          docker push ${{ env.runner_tag }}:latest
